// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SurezeChart.Data;

namespace SurezeChart.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201126123952_CGID_dropped")]
    partial class CGID_dropped
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SurezeChart.Models.Strip", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("HRA")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HRB")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PATIENTID")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SIGNAL")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TOCO")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Strips");
                });
#pragma warning restore 612, 618
        }
    }
}
